# Ceci est un fichier de config Kubernetes

apiVersion: v1
# Type de fichier de configuration
kind: Service
# Metadata du fichier
metadata:
  name: nginx-service
# Spécificité de la ressource
spec:
  # Lier mon service à son déploiement
  selector:
    app: nginx
  ports:
      # port fixe attribué de mes pods
  - port: 8080
      # Protocole de communication
    protocol: TCP
      # port des pods à écouter
    targetPort: 8080  